# Generated by Django 3.2.6 on 2021-08-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pclass', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('age', models.IntegerField()),
                ('sibsp', models.IntegerField()),
                ('parch', models.IntegerField()),
                ('fare', models.IntegerField()),
                ('embarked', models.IntegerField()),
                ('title', models.IntegerField()),
            ],
        ),
    ]
