# Generated by Django 3.2.6 on 2021-08-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
